---
- name: check vcsim container status.
  shell: podman ps -f "name=vcsim" | wc -l
  register: vcsim_container_status
  when: state == "absent"

- name: stop vcsim container.
  command: podman stop vcsim
  register: stop_vcsim_container_result
  when: vcsim_container_status == "2"

- name: delete vcsim container.
  command: podman rm vcsim
  when: stop_vcsim_container_result.rc == 0
