---
- name: install required rpm packages.
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - podman
      - git

- name: install python pip.
  easy_install:
    name: pip

- name: start vCenter Simulator playbook.
  include_tasks: vcenter_simulator_provision.yml
