---
- name: install python pyvmomi module.
  pip:
    name: pyvmomi

- name: clone from ansible repository.
  git:
    repo: "https://github.com/ansible/ansible.git"
    dest: /tmp/ansible
    clone: yes
    version: devel

- name: copy prepare_vmware_tests role.
  copy:
    src: /tmp/ansible/test/integration/targets/prepare_vmware_tests
    dest: "{{ playbook_dir }}/roles/"

- name: delete ansible directory.
  file:
    path: /tmp/ansible
    state: absent

- name: start vcsim container.
  docker_container:
    name: vcsim
    image: quay.io/ansible/vcenter-test-container
    ports:
      - "5000:5000"
      - "443:443"
      - "80:80"
      - "8080:8080"
      - "8989:8989"
    restart: yes
    restart_policy: always
    state: started
  register: docker_container_result
  when: ansible_facts.distribution == "CentOS"

- when: ansible_facts.distribution == "RedHat"
  block:
    - name: pull vcsim container image.
      podman_image:
        name: quay.io/ansible/vcenter-test-container
        state: present

    - name: Gather info vcsim image.
      podman_image_info:
        name: quay.io/ansible/vcenter-test-container
      register: podman_image_info_result

    - name: check vcsim container status.
      shell: podman ps -f "name=vcsim" | wc -l
      register: vcsim_container_status
      when: podman_image_info_result.images

    - name: start vcsim container.
      command: podman run -d -it --name vcsim -p 5000:5000 -p 443:443 -p 80:80 -p 8080:8080 -p 8989:8989 quay.io/ansible/vcenter-test-container
      register: podman_run_result
      when: vcsim_container_status.stdout == "1"

    - name: set podman_run_result.rc valiable.
      set_fact:
        podman_run_result:
          rc: 0
      when: podman_run_result.rc is not defined

- name: start vCenter Simulator.
  command: "ansible-playbook {{ playbook_dir }}/vcenter_simulator.yml -e \"{'state':'present'}\""
  when: docker_container_result.container.State.Status is defined and docker_container_result.container.State.Status == "running" or podman_run_result.rc == 0
